# Generated by Django 4.2.13 on 2024-06-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamers',
            name='friend',
            field=models.ManyToManyField(to='gamers.gamers'),
        ),
        migrations.RemoveField(
            model_name='gamers',
            name='games',
        ),
        migrations.AddField(
            model_name='gamers',
            name='games',
            field=models.ManyToManyField(to='gamers.games'),
        ),
    ]
