# Generated by Django 4.2.13 on 2024-06-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0002_gamers_friend_remove_gamers_games_gamers_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamers',
            name='games',
        ),
        migrations.AddField(
            model_name='games',
            name='gamers',
            field=models.ManyToManyField(to='gamers.gamers'),
        ),
    ]
