# Generated by Django 4.2.13 on 2024-06-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0003_remove_gamers_games_games_gamers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamers',
            name='friend',
            field=models.ManyToManyField(related_name='friends_with', to='gamers.gamers'),
        ),
    ]
