# Generated by Django 4.2.13 on 2024-06-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamers", "0004_alter_gamers_friend"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gamers",
            options={"verbose_name": "Ігроки", "verbose_name_plural": "Ігроки"},
        ),
        migrations.AlterModelOptions(
            name="games",
            options={"verbose_name": "Ігри", "verbose_name_plural": "Ігри"},
        ),
        migrations.AlterModelOptions(
            name="teledata",
            options={
                "verbose_name": "Дані з телеграм",
                "verbose_name_plural": "Дані з телеграм",
            },
        ),
        migrations.AlterField(
            model_name="gamers",
            name="friend",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="friends_with", to="gamers.gamers"
            ),
        ),
    ]
