# Generated by Django 4.2.13 on 2024-06-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamers", "0005_alter_gamers_options_alter_games_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamers",
            name="friend",
            field=models.ManyToManyField(
                blank=True, related_name="friends_with", to="gamers.gamers"
            ),
        ),
        migrations.AlterField(
            model_name="games",
            name="gamers",
            field=models.ManyToManyField(blank=True, to="gamers.gamers"),
        ),
    ]
