# Generated by Django 4.2.13 on 2024-06-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0006_alter_gamers_friend_alter_games_gamers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teledata',
            name='telegram_photo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
